apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ousuf-dev
resources:
  - deployment.yaml

configMapGenerator:
  - name: cluster-config
    literals:
      - environment=production
